version: "3.9"

services:

  db:
    image: timescale/timescaledb:latest-pg15
    container_name: bolsa_timescaledb
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bolsa
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bolsa"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: bolsa_app
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bolsa
    volumes:
      - .:/app

volumes:
  timescale_data:
