version: "3.9"

services:

  db:
    image: timescale/timescaledb:latest-pg15
    container_name: bolsa_timescaledb
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bolsa
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bolsa"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: bolsa_app
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bolsa
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app

  redis:
    image: "redis:alpine"
    container_name: bolsa_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  timescale_data:
  redis_data:
